{% set name = "kalpy" %}
{% set version = "0.6.2" %}

package:
  name: kalpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/kalpy-kaldi/kalpy-kaldi-{{ version }}.tar.gz
  sha256: d15a7319b635238329dea5faaeafd5666c5ceb92d85fd8f738d1be5d70ce01f0

build:
  number: 1
  skip: true  # [py<38]
  run_exports:
    - {{ pin_subpackage('kalpy', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - cmake
    - make                                    # [not win]
    - ninja
    - pybind11
    - setuptools
    - setuptools_scm
  host:
    - python
    - pip
    - kaldi >=5.5.1112
    - openfst ==1.8.3
    - pynini ==2.1.6
  run:
    - python
    - dataclassy
    - numpy
    - librosa
    - praatio
    - openfst ==1.8.3
    - pynini ==2.1.6

test:
  requires:
    # the cuda variant of kaldi requires loading libcuda.so, which we don't have in regular CI
    - kaldi =*=cpu*
    - pytest-order
  imports:
    - _kalpy
    - kalpy

about:
  home: https://github.com/mmcauliffe/kalpy
  summary: 'Pybind11 bindings for Kaldi for use with the Montreal Forced Aligner'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/mmcauliffe/kalpy
  dev_url: https://github.com/mmcauliffe/kalpy

extra:
  recipe-maintainers:
    - mmcauliffe
