{% set name = "kalpy" %}
{% set version = "0.5.1" %}

package:
  name: kalpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/kalpy-kaldi/kalpy-kaldi-{{ version }}.tar.gz
  sha256: 975c97180ccd78ca8f4bfa93ed164ae4c82098e75935c2801c4983890a3a3c7c

build:
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - cmake
    - make                                    # [not win]
    - ninja
    - pybind11
    - setuptools
    - setuptools_scm
  host:
    - python
    - pip
    - kaldi
    - openfst
    - pynini
  run:
    - python
    - dataclassy
    - numpy
    - librosa
    - praatio

test:
  requires:
    # the cuda variant of kaldi requires loading libcuda.so, which we don't have in regular CI
    - kaldi =*=cpu*
    - pytest-order
  imports:
    - _kalpy
    - kalpy

about:
  home: https://github.com/mmcauliffe/kalpy
  summary: 'Pybind11 bindings for Kaldi for use with the Montreal Forced Aligner'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/mmcauliffe/kalpy
  dev_url: https://github.com/mmcauliffe/kalpy

extra:
  recipe-maintainers:
    - mmcauliffe
