{% set version = "0.9.0" %}
{% set kaldi_version = "5.5.1172" %}
{% set openfst_version = "1.8.4" %}

package:
  name: kalpy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/k/kalpy-kaldi/kalpy_kaldi-{{ version }}.tar.gz
  sha256: 54982b845bb4d13bb909c0c40c5300d78fe0207a840be11543ccf21fd26e8673

build:
  number: 1
  run_exports:
    strong:
      - kalpy

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python                                    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}        # [build_platform != target_platform]
    - setuptools                                # [build_platform != target_platform]
    - setuptools_scm                            # [build_platform != target_platform]
    - cmake
    - make                                      # [not win]
    - ninja
    - pybind11
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - kaldi {{ kaldi_version }}
    - openfst =={{ openfst_version }}
    - pynini
  run:
    - python
    - numpy
    - librosa
    - pyyaml
    - praatio
    - openfst =={{ openfst_version }}
    - pynini
    - kaldi {{ kaldi_version }}

test:
  imports:
    - kalpy
    - kalpy.aligner
    - kalpy.data
    - kalpy.evaluation
    - kalpy.exceptions
    - kalpy.models
    - kalpy.utils
    - kalpy.utterance
    - kalpy.decoder
    - kalpy.decoder
    - kalpy.decoder.data
    - kalpy.decoder.decode_graph
    - kalpy.decoder.training_graphs
    - kalpy.feat
    - kalpy.feat.cmvn
    - kalpy.feat.data
    - kalpy.feat.fmllr
    - kalpy.feat.lda
    - kalpy.feat.mfcc
    - kalpy.feat.pitch
    - kalpy.feat.vad
    - kalpy.fstext
    - kalpy.fstext.lexicon
    - kalpy.fstext.utils
    - kalpy.gmm
    - kalpy.gmm.align
    - kalpy.gmm.data
    - kalpy.gmm.decode
    - kalpy.gmm.train
    - kalpy.gmm.utils

about:
  home: https://github.com/mmcauliffe/kalpy
  summary: 'Pybind11 bindings for Kaldi for use with the Montreal Forced Aligner'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/mmcauliffe/kalpy
  dev_url: https://github.com/mmcauliffe/kalpy

extra:
  recipe-maintainers:
    - mmcauliffe
