{% set version = "0.9.0" %}
{% set kaldi_version = "5.5.1172" %}
{% set openfst_version = "1.8.4" %}
{% set proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

package:
  name: kalpy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/k/kalpy-kaldi/kalpy_kaldi-{{ version }}.tar.gz
  sha256: 060567965a29be7596d8f878ea0d699c2ae287d8bafc1e6d6d02207c11d89318

build:
  number: 0
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}                                                # [cuda_compiler_version == "None"]
  run_exports:
    strong:
      - kalpy
  missing_dso_whitelist:
    - "*/nvcuda.dll"   # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ compiler('cuda') }}                    # [cuda_compiler_version != "None"]
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - python                                    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}        # [build_platform != target_platform]
    - setuptools                                # [build_platform != target_platform]
    - setuptools_scm                            # [build_platform != target_platform]
    - cmake
    - make                                      # [not win]
    - ninja
    - pybind11
  host:
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - python
    - pip
    - setuptools
    - setuptools_scm
    - kaldi {{ kaldi_version }} {{ proc_type }}*
    - openfst =={{ openfst_version }}
    - pynini
  run:
    - python
    - numpy
    - librosa
    - pyyaml
    - praatio
    - openfst =={{ openfst_version }}
    - pynini
    - kaldi {{ kaldi_version }} {{ proc_type }}*

test:
  imports:
    - kalpy
    {% if cuda_compiler_version == "None" %}
    # using the cuda version wants to load libcuda.so.1 which we don't have
    - kalpy.aligner
    - kalpy.data
    - kalpy.evaluation
    - kalpy.exceptions
    - kalpy.models
    - kalpy.utils
    - kalpy.utterance
    - kalpy.decoder
    - kalpy.decoder
    - kalpy.decoder.data
    - kalpy.decoder.decode_graph
    - kalpy.decoder.training_graphs
    - kalpy.feat
    - kalpy.feat.cmvn
    - kalpy.feat.data
    - kalpy.feat.fmllr
    - kalpy.feat.lda
    - kalpy.feat.mfcc
    - kalpy.feat.pitch
    - kalpy.feat.vad
    - kalpy.fstext
    - kalpy.fstext.lexicon
    - kalpy.fstext.utils
    - kalpy.gmm
    - kalpy.gmm.align
    - kalpy.gmm.data
    - kalpy.gmm.decode
    - kalpy.gmm.train
    - kalpy.gmm.utils
    {% endif %}

about:
  home: https://github.com/mmcauliffe/kalpy
  summary: 'Pybind11 bindings for Kaldi for use with the Montreal Forced Aligner'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/mmcauliffe/kalpy
  dev_url: https://github.com/mmcauliffe/kalpy

extra:
  recipe-maintainers:
    - mmcauliffe
