{% set name = "kalpy" %}
{% set version = "0.6.5" %}
{% set proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

package:
  name: kalpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/kalpy-kaldi/kalpy_kaldi-{{ version }}.tar.gz
  sha256: 4864e70c179c0915cc201d477afac267e5fbfdf5a750b1b183c8d7a467858a72

build:
  number: 1
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  run_exports:
    strong:
      - kalpy
  missing_dso_whitelist:
    - "*/nvcuda.dll"   # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ compiler('cuda') }}                    # [cuda_compiler_version != "None"]
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - python                                    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}        # [build_platform != target_platform]
    - setuptools                                # [build_platform != target_platform]
    - setuptools_scm                            # [build_platform != target_platform]
    - cmake
    - make                                      # [not win]
    - ninja
    - pybind11
  host:
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - python
    - pip
    - setuptools
    - setuptools_scm
    - kaldi =5.5.1112={{ proc_type }}*
    - openfst ==1.8.3
    - pynini ==2.1.6
  run:
    - python
    - dataclassy
    - numpy
    - librosa
    - praatio
    - openfst ==1.8.3
    - pynini ==2.1.6
  run_constrained:
    - kaldi =5.5.1112={{ proc_type }}*

about:
  home: https://github.com/mmcauliffe/kalpy
  summary: 'Pybind11 bindings for Kaldi for use with the Montreal Forced Aligner'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/mmcauliffe/kalpy
  dev_url: https://github.com/mmcauliffe/kalpy

extra:
  recipe-maintainers:
    - mmcauliffe
