{% set name = "kalpy" %}
{% set version = "0.6.1" %}

package:
  name: kalpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/kalpy-kaldi/kalpy-kaldi-{{ version }}.tar.gz
  sha256: 4bb06f63506ec11155dd717b7dc248ae9ae4283fe052dc51ad0a51dc821f9d18

build:
  number: 1
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - cmake
    - make                                    # [not win]
    - ninja
    - pybind11
    - setuptools
    - setuptools_scm
  host:
    - python
    - pip
    - kaldi >=5.5.1068
    - openfst ==1.8.2
    - pynini ==2.1.5
  run:
    - python
    - dataclassy
    - numpy
    - librosa
    - praatio
    - openfst ==1.8.2
    - pynini ==2.1.5

test:
  requires:
    # the cuda variant of kaldi requires loading libcuda.so, which we don't have in regular CI
    - kaldi =*=cpu*
    - pytest-order
  imports:
    - _kalpy
    - kalpy

about:
  home: https://github.com/mmcauliffe/kalpy
  summary: 'Pybind11 bindings for Kaldi for use with the Montreal Forced Aligner'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/mmcauliffe/kalpy
  dev_url: https://github.com/mmcauliffe/kalpy

extra:
  recipe-maintainers:
    - mmcauliffe
