{% set name = "kalpy" %}
{% set version = "0.7.0" %}
{% set kaldi_version = "5.5.1112" %}
{% set openfst_version = "1.8.3" %}

package:
  name: kalpy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/k/kalpy-kaldi/kalpy_kaldi-{{ version }}.tar.gz
  sha256: 43848465aac8688ec78b380f4e1714e3b211da77ae6efe8def4385f1155ba658

build:
  number: 0
  run_exports:
    strong:
      - kalpy

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python                                    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}        # [build_platform != target_platform]
    - setuptools                                # [build_platform != target_platform]
    - setuptools_scm                            # [build_platform != target_platform]
    - cmake
    - make                                      # [not win]
    - ninja
    - pybind11
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - kaldi {{ kaldi_version }} cpu
    - openfst =={{ openfst_version }}
    - pynini
  run:
    - python
    - dataclassy
    - numpy
    - librosa
    - praatio
    - openfst =={{ openfst_version }}
    - pynini
    - kaldi {{ kaldi_version }} cpu

about:
  home: https://github.com/mmcauliffe/kalpy
  summary: 'Pybind11 bindings for Kaldi for use with the Montreal Forced Aligner'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/mmcauliffe/kalpy
  dev_url: https://github.com/mmcauliffe/kalpy

extra:
  recipe-maintainers:
    - mmcauliffe
